# Generated by Django 3.2.5 on 2021-07-20 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authy', '0002_rating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
